version: "3.7"
services:
  kafka:
    image: wurstmeister/kafka:${CONTAINER_KAFKA_VERSION:-2.12-2.4.0}
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: wurstmeister/zookeeper
  code:
    build:
      context: .
      args:
        - CONTAINER_RUBY_VERSION=${CONTAINER_RUBY_VERSION:-2.7.0}
    image: kafka_party
    links:
      - kafka
      - zookeeper
    volumes:
      - .:/code
